environment:
  global:
    PACKAGE: "Dart"

  matrix:
    - SUBLIME_TEXT_VERSION : "3"

install:
  # TODO: Use Desired state configuration or a block script.
  - git submodule update --init --recursive
  - ps: start-filedownload "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
  - ps: .\appveyor.ps1 "bootstrap" -verbose

build: off

test_script:
  - ps: .\appveyor.ps1 "run_tests" -verbose
